# Generated by Django 3.0.8 on 2020-07-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='OtherCategory', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vendor_category', to='profileapp.Category')),
                ('vendor', models.ForeignKey(default='OtherVendor', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vendor_category', to='profileapp.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(related_name='vendors', through='profileapp.VendorCategory', to='profileapp.Category'),
        ),
    ]
