# Generated by Django 3.0.8 on 2020-07-15 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categories', to='profileapp.Category')),
                ('vendor', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vendors', to='profileapp.Vendor')),
            ],
            options={
                'verbose_name_plural': 'certifications',
            },
        ),
    ]
