# Generated by Django 3.0.8 on 2020-07-15 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0002_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('certification', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vendor_certs', to='profileapp.Certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_certs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vendor certifications',
            },
        ),
    ]
