# Generated by Django 3.0.8 on 2020-07-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_vendorcertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcertification',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vendorcertification',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
